<a href="https://colab.research.google.com/github/IskanderRyspaevUniDubna/MyPractise2022/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_2022_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Задание №4**

\begin{equation}
  \int\frac{dp}{\pi^2}F(p^2)\frac{1}{((p+q_1)^2+m_1^2)((p+q_2)^2+m_2^2)((p+q_3)^2+m_3^2)}=-\int[d\alpha]_3\frac{t^2}{(1+t)^2}dt\cdot F^{'}[z_0]
\end{equation}

\begin{equation}
  D=\alpha_1(q_1^2+m_1^2)+\alpha_2(q_2^2+m_2^2)+\alpha_3(q_3^2+m_3^2)-R^2
\end{equation}
\begin{equation}
  R^2=\alpha_1^2q_1^2+\alpha_2^2q_2^2+\alpha_3^2q_3^2+\alpha_1\alpha_2(2q_1q_2)+\alpha_2\alpha_3(2q_2q_3)+\alpha_1\alpha_3(2q_1q_3)
\end{equation}

\begin{equation}
z_0 = tD + \frac{t}{1 + t} R^2
\end{equation}
\begin{equation}
  F[z_0] = e^{-z_0}
\end{equation}

Пусть нам даны матрицы $Q$ и $M$:
$$Q = \begin{pmatrix}q_1\\q_2\\q_3\end{pmatrix}$$
$$M = \begin{pmatrix}m_1\\m_2\\m_3\end{pmatrix}$$

In [1]:
import numpy as np
Q = np.array([1,1,1])
M = np.array([1,1,1])
print(Q)
print(M)

[1 1 1]
[1 1 1]


Введём матрицы $A$, $B$ и $C$ по следущим правилам:
\begin{equation}
  A = \begin{pmatrix}q_1^2\\q_2^2\\q_3^2\end{pmatrix} \;\;\;\;\;\;
  B = \begin{pmatrix}2q_1q_2\\2q_2q_3\\2q_1q_3\end{pmatrix} \;\;\;\;\;\;
  C = \begin{pmatrix}q_1^2+m_1^2\\q_2^2+m_2^2\\q_3^2+m_3^2\end{pmatrix}
\end{equation}

In [2]:
A = np.empty(3)
B = np.empty(3)
C = np.empty(3)
B[0] = 2 * Q[0] * Q[1]
B[1] = 2 * Q[1] * Q[2]
B[2] = 2 * Q[0] * Q[2]
for i in range(0,3):
  A[i] = Q[i] * Q[i]
  C[i] = Q[i] * Q[i] + M[i] * M[i]
print(C)

[2. 2. 2.]


По условию задания:
$$\alpha_1$$
$$\alpha_2 = 1 - \alpha_1$$
$$\alpha_3 = 1 - \alpha_1 - \alpha_2$$
Пусть $\alpha_1=x\;\;$$\alpha_2=y\;\;$$\alpha_3=z$. Тогда получим, что:
$$x$$
$$y = 1 - x$$
$$z = 1 - x - y$$


\begin{equation}
  D=\alpha_1(q_1^2+m_1^2)+\alpha_2(q_2^2+m_2^2)+\alpha_3(q_3^2+m_3^2)-R^2
\end{equation}
\begin{equation}
  R^2=\alpha_1^2q_1^2+\alpha_2^2q_2^2+\alpha_3^2q_3^2+\alpha_1\alpha_2(2q_1q_2)+\alpha_2\alpha_3(2q_2q_3)+\alpha_1\alpha_3(2q_1q_3)
\end{equation}

In [3]:
import sympy as sym
x = sym.Symbol('x')
y = sym.Symbol('y')
z = sym.Symbol('z')
RR = (x**2)*A[0] + (y**2)*A[1] + (z**2)*A[2] + x*y*B[0] + y*z*B[1] + x*z*B[2]
D = x * C[0] + y * C[1] + z * C[2] - RR 

Возьмем производную от выражения $F[z_0] = e^{-z_0}$ по $z_0$ и получим:
$$F^{'}[z_0] = -e^{-z_0}$$

По определению $z$:
\begin{equation}
z_0 = tD + \frac{t}{1 + t} R^2
\end{equation}

In [4]:
import sympy as sym
x = sym.Symbol('x')
y = sym.Symbol('y')
z = sym.Symbol('z')
t = sym.Symbol('t')

z_0 = t * D + ((t)/(1+t))*RR

F_z_0 = -sym.exp(-z_0)
source_expression = (t**2)/((1+t)**3) * F_z_0
print(source_expression)

-t**2*exp(-t*(-1.0*x**2 - 2.0*x*y - 2.0*x*z + 2.0*x - 1.0*y**2 - 2.0*y*z + 2.0*y - 1.0*z**2 + 2.0*z) - t*(1.0*x**2 + 2.0*x*y + 2.0*x*z + 1.0*y**2 + 2.0*y*z + 1.0*z**2)/(t + 1))/(t + 1)**3


In [5]:
import mcint
import random
import math
import numpy as np
def integrand(variable):
    x = variable[0]
    y = variable[1]
    z = variable[2]
    t = variable[3]
    return (-t**2*math.exp(-t*(-1.0*x**2 - 2.0*x*y - 2.0*x*z + 2.0*x - 1.0*y**2 - 2.0*y*z + 2.0*y - 1.0*z**2 + 2.0*z) - t*(1.0*x**2 + 2.0*x*y + 2.0*x*z + 1.0*y**2 + 2.0*y*z + 1.0*z**2)/(t + 1))/(t + 1)**3)
def sampler():
    while True:
        x = random.uniform(0,1)
        y = random.uniform(0,1-x)
        z = random.uniform(0,1-x-y)
        t = random.uniform(0, 80000)
        yield (x,y,z,t)
result, error = mcint.integrate(integrand, sampler())
print(result)

-1.7395630836468197e-164


In [6]:
pip install mcint

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


[О библиотеке mcint](https://overcoder.net/q/327403/%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D0%BB%D0%B0-%D0%B2-scipy)

[SymPy](https://www.inp.nsk.su/~grozin/python/b25_sympy.html)

[Сайт для ввода формул в ЛаТеХ](https://latexeditor.lagrida.com/)

[Питон в научных вычислениях](https://inp.nsk.su/~grozin/python/python7.html)

[Язык Python 3 для научных исследований](https://docs.yandex.ru/docs/view?tm=1657306821&tld=ru&lang=ru&name=SymPy2017.pdf&text=SymPy%20%D1%87%D0%B8%D1%81%D0%BB%D0%BE%20e&url=http%3A%2F%2Fvgupetrova.ru%2Fwp-content%2Fuploads%2F2019%2F11%2FSymPy2017.pdf&lr=215&mime=pdf&l10n=ru&sign=45a938649a70505efdc10f3cb7990435&keyno=0&nosw=1&serpParams=tm%3D1657306821%26tld%3Dru%26lang%3Dru%26name%3DSymPy2017.pdf%26text%3DSymPy%2B%25D1%2587%25D0%25B8%25D1%2581%25D0%25BB%25D0%25BE%2Be%26url%3Dhttp%253A%2F%2Fvgupetrova.ru%2Fwp-content%2Fuploads%2F2019%2F11%2FSymPy2017.pdf%26lr%3D215%26mime%3Dpdf%26l10n%3Dru%26sign%3D45a938649a70505efdc10f3cb7990435%26keyno%3D0%26nosw%3D1)

[Как получить из ipynb pdf или ЛаТеХ](https://)